# Generated by Django 5.2.13 on 2026-04-29 08:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Category Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Vendor Name')),
                ('mobile', models.CharField(max_length=20, verbose_name='Mobile Number')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('bank_account', models.CharField(blank=True, max_length=200, null=True, verbose_name='Bank Account Details')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Product Name')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Purchase Price (৳)')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Selling Price (৳)')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Current Stock')),
                ('opening_stock', models.PositiveIntegerField(default=0, verbose_name='Opening Stock')),
                ('low_stock_threshold', models.PositiveIntegerField(default=10, verbose_name='Low Stock Alert Threshold')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='inventory.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('IN', 'Stock IN (Purchase/Receive)'), ('OUT', 'Stock OUT (Sale/Issue)')], max_length=3, verbose_name='Transaction Type')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note/Reason')),
                ('voucher_number', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Voucher Number')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date & Time')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_logs', to='inventory.product', verbose_name='Product')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_logs', to='inventory.vendor', verbose_name='Vendor')),
            ],
            options={
                'verbose_name': 'Stock Log',
                'verbose_name_plural': 'Stock Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
