# Generated by Django 5.2.13 on 2026-05-03 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_product_vendor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusStockLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('IN', 'Stock IN'), ('OUT', 'Stock OUT')], max_length=3, verbose_name='Type')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campus_stock_logs', to='inventory.campus', verbose_name='Campus')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campus_stock_logs', to='inventory.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Campus Stock Log',
                'verbose_name_plural': 'Campus Stock Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
